---
- hosts: balancer
  remote_user: root
  become: yes
  vars:
    user: deploy
  tasks:
    - name: Update all packages to the latest version
      apt:
        upgrade: dist
    - name: Add deploy user
      user:
        name: deploy
        shell: /bin/bash
    - name: Add SSH key to server for deploy user
      authorized_key:
        user: deploy
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC8X8gmGN+zwz6yFIOesdE0M6MwG9DMsf/TJhfRYmXz7X9S30Vi5RUVU9KZoukoWhz5vC/eeE8q1BFCGYmLHXY3Pv1N/e+1AryL00jaN22RYyXrE13iXN5rJ6aEZGP85kNf8KldoBtlPcHoo+iOIKbpUvpBPHY7pZEoa3WgKflgvQ10PjBvKDZLzVtwD4xmajuKA/vctiQ1h/MgXcXoEK3pDjTO9CleBYmfH+KObJfDvKoibsGh28bmGT0OiO+NbvIIq7Is2ZFPFFa/XohzUq0SHzB9onvAj8CtdEMgz7mGGs8GFDBOM6lS8hMDQvP+fnAoBuoHxOXVL7KDQB1GtGFX me@ferperales.net"
    - name: Install NGINX
      apt:
        name: ['nginx']
        update_cache: yes
    - name: Ansible delete file example
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
    - name: copy nginx configuration file
      template:
        src: nginx.conf.balancer
        dest: /etc/nginx/conf.d/load-balancer.conf
        owner: root
        group: root
        mode: u=rw,g=r,o=r
      notify: restart nginx


  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
